# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-29 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='units',
            field=models.IntegerField(),
        ),
    ]
