# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-27 20:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('features', django.contrib.postgres.fields.jsonb.JSONField()),
                ('price', models.FloatField()),
                ('units', models.IntegerField()),
                ('active', models.CharField(choices=[('active', 'Currently Selling'), ('inactive', 'Not Up For Sale')], default='active', max_length=15)),
            ],
        ),
    ]
