# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-29 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financialaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_ledgers', to='order.Order'),
        ),
    ]
